name: npm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - name: Set up Haxe
      run: |
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: v12.x
    - name: Install npm dependencies
      run: npm ci
    - name: Build npm module
      run: npm run build